modLoader="javafml"
loaderVersion="[${forgeVersionRange},)"
license="https://github.com/danilppzz/danilppzz/blob/main/LICENSE"
issueTrackerURL="https://github.com/danilppzz/PotLeaves/issues"

[[mods]]
modId="potleaves"
version="${modVersion}"
displayName="Pot Leaves"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://danilppzz.dev/"
logoFile="potleaves.png"
credits="3D models made with Blockbench"
authors="danilppzz"


description='''
This mod is very simple, it basically adds a bunch of pots with different plants.
Some of them have special functions like attracting some mobs/animals, or other functions like foot farming and more.
'''

[[dependencies.potleaves]]
modId="forge"
mandatory=true
versionRange="[${forgeVersionRange},)"
ordering="NONE"
side="BOTH"
[[dependencies.potleaves]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
[[dependencies.potleaves]]
modId="architectury"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"
